package controllers;

import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import application.Coin;
import application.DatabaseConnection;
import application.EternalGoal;
import application.Master;
import dialogs.ErrDialog;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;

public class EternalGoalAddController extends MasterController implements Initializable {
	@FXML
	private TextField time;
	@FXML
	private Button goalAddBtn;
	@FXML
	private Button cancelBtn;
	@FXML
	private TextField minute;
	@FXML
	private ComboBox<Coin> coinSelect;

	private String tableName = "coin";

	private String coinIDColumnName = "CoinID";

	private String coinNameColumnName = "CoinName";

	// Event Listener on Button[#goalAddBtn].onAction
	@FXML
	public void onGoalAddBtn(ActionEvent event) {
		// TODO Autogenerated
		if(coinSelect.getValue() == null) {
			ErrDialog.noCoinSelectedErr();
		}
		else {
			try {
				int i_time = Integer.parseInt(time.getText());
				int i_minute = Integer.parseInt(minute.getText());
				EternalGoal eg = new EternalGoal();
				int amount = i_time * 60 + i_minute;
				eg.set(amount, coinSelect.getValue().getCoinID());
				if(eg.insert()) {
					Master.closeSubStage();

				}

			}catch (NumberFormatException e) {
				// TODO: handle exception
				ErrDialog.noNumberErr();
			}
		}
	}
	// Event Listener on Button[#cancelBtn].onAction
	@FXML
	public void onCancelBtn(ActionEvent event) {
		// TODO Autogenerated
		Master.closeSubStage();
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO 自動生成されたメソッド・スタブ
		DatabaseConnection db = new DatabaseConnection(databaseFilePath);
		ResultSet rs;
		try {
			coinSelect.getItems().clear();
			rs = db.select("select * from " + tableName);
			int index = 0;
			while(rs.next()) {
				Coin tmp = new Coin(index,rs.getInt(coinIDColumnName),rs.getString(coinNameColumnName));
				coinSelect.getItems().add(tmp);
				index++;
			}
			rs.close();
			db.close();

		} catch (SQLException e) {
			// TODO 自動生成された catch ブロック
			ErrDialog.databaseErr();
		}

	}
}
