package controllers;

import java.net.URL;
import java.util.ResourceBundle;

import application.EternalGoal;
import application.Master;
import dialogs.ErrDialog;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;

public class EternalGoalEditController extends MasterController implements Initializable {
	@FXML
	private TextField time;
	@FXML
	private Button goalAddBtn;
	@FXML
	private Button cancelBtn;
	@FXML
	private TextField minute;

	private EternalGoal nowEdit = EternalGoal.nowEdit;

	// Event Listener on Button[#goalAddBtn].onAction
	@FXML
	public void onGoalAddBtn(ActionEvent event) {
		// TODO Autogenerated
		try {
			int time = Integer.parseInt(this.time.getText());
			int minute = Integer.parseInt(this.minute.getText());
			nowEdit.set(time * 60 + minute);
			if(nowEdit.update()) {
				Master.closeSubStage();
			}
		}catch (NumberFormatException e) {
			// TODO: handle exception
			ErrDialog.noNumberErr();
		}
	}
	// Event Listener on Button[#cancelBtn].onAction
	@FXML
	public void onCancelBtn(ActionEvent event) {
		// TODO Autogenerated
		Master.closeSubStage();
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO 自動生成されたメソッド・スタブ
		time.setText(Integer.toString(nowEdit.getAmount() / 60));
		minute.setText(Integer.toString(nowEdit.getAmount() % 60));
	}
}
